site_name: backstage-plugin-techdocs-addon-dbml
site_description: Fixture TechDocs site for developing the DBML addon
nav:
  - Home: index.md
  - Examples:
      - Overview: example/index.md
      - Simple schema: example/samples/simple.md
      - Large schema: example/samples/large.md
      - Invalid DBML: example/samples/invalid.md
plugins:
  - techdocs-core
